name: Mark stale issues

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale due to inactivity for 5 days.'
        remove-stale-when-updated: true 
        stale-issue-label: 'stale'
        days-before-stale: 5
        operations-per-run: 30  # Adjust as needed
